apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dataops-cronjob
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: dataops
              image: us-west2-docker.pkg.dev/gao-hongnan/thebareops/pipeline-dataops:your-image-tag
              env:
                - name: PROJECT_ID
                  value: "your-project-id"
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/google/key.json
          volumes:
            - name: google-cloud-key
              secret:
                secretName: google-cloud-key
          restartPolicy: OnFailure

          env: # we extract the values we set in the configmap and mount them as environmen variables in the pods.
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mlflow-tracking-server-database-postgresql
                key: postgresql-password
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_USERNAME
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_URL
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_NAME
          - name: ARTIFACT_STORE
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: ARTIFACT_STORE