apiVersion: batch/v1
kind: CronJob
metadata:
  name: dataops-cronjob
  labels:
    app: dataops
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      replicas: 3
      template:
        spec:
          containers:
            - name: dataops-pod
              image: us-west2-docker.pkg.dev/gao-hongnan/thebareops/pipeline-dataops:0a3db7efb5eba6abb6a56e4c0ced3a416444f783
              imagePullPolicy: Always
              env: # we extract the values we set in the configmap and mount them as environmen variables in the pods.
                - name: PROJECT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: pipeline-dataops-config
                      key: PROJECT_ID
                - name: GCS_BUCKET_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: pipeline-dataops-config
                      key: GCS_BUCKET_NAME
                - name: GCS_BUCKET_PROJECT_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: pipeline-dataops-config
                      key: GCS_BUCKET_PROJECT_NAME
                - name: BIGQUERY_RAW_DATASET
                  valueFrom:
                    configMapKeyRef:
                      name: pipeline-dataops-config
                      key: BIGQUERY_RAW_DATASET
                - name: BIGQUERY_RAW_TABLE_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: pipeline-dataops-config
                      key: BIGQUERY_RAW_TABLE_NAME
                - name: BIGQUERY_TRANSFORMED_DATASET
                  valueFrom:
                    configMapKeyRef:
                      name: pipeline-dataops-config
                      key: BIGQUERY_TRANSFORMED_DATASET
                - name: BIGQUERY_TRANSFORMED_TABLE_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: pipeline-dataops-config
                      key: BIGQUERY_TRANSFORMED_TABLE_NAME
                - name: GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64
                  valueFrom:
                    secretKeyRef:
                      name: pipeline-dataops-secret
                      key: GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/google/gcp-storage-service-account.json
              volumeMounts:
                - name: google-cloud-credentials
                  mountPath: /var/secrets/google
                  readOnly: true
              # envFrom: # this is an alternative to env, it allows you to mount all the values in a configmap as environment variables.
              #   - configMapRef:
              #       name: pipeline-dataops-config
              #   - secretRef:
              #       name: pipeline-dataops-secret
          volumes:
            - name: google-cloud-credentials
              secret:
                secretName: dataops-gcp-credentials-base64
          restartPolicy: OnFailure
