name: Deploy DataOps Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy_dataops_pipeline:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64 }}
      GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
      GCS_BUCKET_PROJECT_NAME: ${{ secrets.GCS_BUCKET_PROJECT_NAME }}
      BIGQUERY_RAW_DATASET: ${{ secrets.BIGQUERY_RAW_DATASET }}
      BIGQUERY_RAW_TABLE_NAME: ${{ secrets.BIGQUERY_RAW_TABLE_NAME }}
      BIGQUERY_TRANSFORMED_DATASET: ${{ secrets.BIGQUERY_TRANSFORMED_DATASET }}
      BIGQUERY_TRANSFORMED_TABLE: ${{ secrets.BIGQUERY_TRANSFORMED_TABLE }}
      HOME_DIR: ${{ secrets.HOME_DIR }}
      REPO_NAME: imdb-repo  # Set this to your Artifact Registry repository name
      REGION: us-west2

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ env.GOOGLE_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Configure Docker to use gcloud for authentication
      run: |
        echo "Configuring Docker to use gcloud for authentication..."
        gcloud auth configure-docker ${REGION}-docker.pkg.dev

    # - name: Cache Docker layers
    #   uses: satackey/action-docker-layer-caching@v0.0.11
    #   # Ignore the failure of a step and avoid terminating the job.
    #   continue-on-error: true

    - name: Build Docker image
      run: |
        echo "Building Docker image..."
        docker build \
        -f docker/serve.Dockerfile \
        -t "${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${APP_NAME}:v1" \
        .

    - name: Push Docker image to Google Artifact Registry
      run: |
        echo "Pushing Docker image..."
        docker push \
        "${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${APP_NAME}:v1"
        echo "Docker image built and pushed to Google Artifact Registry"

    # - name: Deploy to Cloud Run
    #   run: |
    #     echo "Deploying to Cloud Run..."
    #     gcloud run deploy ${APP_NAME} \
    #     --image "${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${APP_NAME}:v1" \
    #     --region ${REGION} \
    #     --memory 2G \
    #     --platform managed \
    #     --allow-unauthenticated \
    #     --no-cpu-throttling \
    #     --update-env-vars=GOOGLE_SERVICE_ACCOUNT_BASE64="${{ secrets.GOOGLE_SERVICE_ACCOUNT_BASE64 }}"
    #     echo "Successfully deployed to Google Cloud Run"